routes/web.php
<?php

Auth::routes();

Route::group(['prefix' => '/'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('news', 'NewsController@index')->name('news-list');
    Route::get('news/{id}', 'NewsController@show')->name('news-show');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::get('reviews', 'ReviewController@index')->name('reviews');
    Route::post('mail', 'ContactController@sendEmail')->name('send-mail');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth',], function () {

    Route::get('/', 'Admin\HomeController@index')->name('admin.index');

    Route::resource('product', 'Admin\ProductController')->except([
        'show'
    ]);

    Route::resource('news', 'Admin\NewsController')->except([
        'show'
    ]);

    Route::resource('review', 'Admin\ReviewController')->except([
        'show'
    ]);

    Route::resource('contacts-email', 'Admin\ContactsEmailController')->except([
        'show'
    ]);

    Route::resource('contacts', 'Admin\ContactsController')->except([
        'show'
    ]);

    Route::resource('customers', 'Admin\CustomerController')->except([
        'show'
    ]);

    Route::post('image-upload/{id}', 'Admin\ProductImagesController@upload');

    Route::post('image-destroy/{id}', 'Admin\ProductImagesController@destroy');

    Route::post('image-store', 'Admin\ProductImagesController@store');
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Support\Carbon;

/**
 * App\Models\Customer
 *
 * @method static Builder|Customer newModelQuery()
 * @method static Builder|Customer newQuery()
 * @method static Builder|Customer query()
 * @mixin \Eloquent
 * @property int $id
 * @property string|null $name
 * @property float|null $latitude
 * @property float|null $longitude
 * @property string $description
 * @property int $status
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Collection|Product[] $product
 * @method static Builder|Customer whereCreatedAt($value)
 * @method static Builder|Customer whereDescription($value)
 * @method static Builder|Customer whereId($value)
 * @method static Builder|Customer whereLatitude($value)
 * @method static Builder|Customer whereLongitude($value)
 * @method static Builder|Customer whereName($value)
 * @method static Builder|Customer whereStatus($value)
 * @method static Builder|Customer whereUpdatedAt($value)
 */
class Customer extends Model
{
    /**
     * @var string
     */
    protected $table = 'customers';

    /**
     * @var array
     */
    protected $fillable = ['name', 'latitude', 'longitude', 'description'];

    /**
     * @return BelongsToMany
     */
    public function product(): BelongsToMany
    {
        return $this->belongsToMany(Product::class, 'customer_products', 'cus_id', 'prdct_id');
    }

}

app/Http/Controllers/Admin/CustomerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CustomerRequest;
use App\Models\Customer;
use App\Models\Product;
use Illuminate\Http\Response;
use Illuminate\View\View;

class CustomerController extends Controller
{
    /**
     * CustomerController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['only' => ['index', 'edit', 'update', 'store', 'destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $customers = Customer::paginate(10);
        return view('admin.customers.list', compact('customers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        $products = Product::get();
        return view('admin.customers.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CustomerRequest $request
     * @return View
     */
    public function store(CustomerRequest $request): View
    {
        $customer = new Customer([
            'name'        => $request->get('name'),
            'latitude'    => $request->get('latitude'),
            'longitude'   => $request->get('longitude'),
            'description' => $request->get('body'),
        ]);
        $products = $request->input('products');
        $customer->product()->sync($products);
        $customer->save();

        return back()->with('success', 'Stock has been added');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit(int $id): View
    {
        $customers = Customer::FindorFail($id)->firstOrFail();
        $products = Product::get();
        return view('admin.customers.edit', [
            'customers' => $customers,
            'products'  => $products
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CustomerRequest $request
     * @param int $id
     * @return View
     */
    public function update(CustomerRequest $request, int $id): View
    {
        $customer = Customer::findOrFail($id);
        $customer->name = $request->get('name');
        $customer->latitude = $request->get('latitude');
        $customer->longitude = $request->get('longitude');
        $products = $request->input('products');
        $customer->product()->sync($products);
        $customer->save();

        return back()->with('success', 'Customer has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return View
     */
    public function destroy(int $id): View
    {
        $customer = Customer::findorfail($id);
        if ($customer->status == 0) {
            $customer->status = '1';
        } elseif ($customer->status == 1) {
            $customer->status = '0';
        }
        $customer->save();
        return back();
    }
}

resources/views/admin/customers/create.blade.php
@extends('admin.layouts.app')

@section('title')
    Create customers
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('vendors/summernote/dist/summernote-bs4.css')}}">
@stop

@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row grid-margin">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-start justify-content-between">
                                <h4 class="card-title">Customers create</h4>
                                <a href="{{ route("customers.index") }}" class="btn btn-primary btn-sm">Return to
                                    list</a>
                            </div>
                            @if(session()->has('success'))
                                <div class="alert alert-success">
                                    {{ session()->get('success') }}
                                </div>
                            @endif
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('customers.store') }}" enctype="multipart/form-data" method="POST">
                                @csrf
                                <div class="media">
                                    <div class="card-body">
                                        <div class="form-group">
                                            <label for="name">Title</label>
                                            <input type="text" value="{{Request::old('name')}}"
                                                   name="name"
                                                   class="form-control" id="name"
                                                   placeholder="Name">
                                        </div>
                                        <div class="form-group">
                                            <label for="latitude">Latitude</label>
                                            <input type="number" step="any" value="{{Request::old('latitude')}}"
                                                   name="latitude" class="form-control" id="latitude">
                                        </div>
                                        <div class="form-group">
                                            <label for="longitude">Longitude</label>
                                            <input type="number" step="any" value="{{Request::old('longitude')}}"
                                                   name="longitude" class="form-control" id="longitude">
                                        </div>
                                        <div class="form-group">
                                            <textarea id="description" name="body"></textarea>
                                        </div>
                                        <div class="form-group">
                                            <label>List of related products</label>
                                            <select class="js-example-basic-multiple" name="products[]" multiple="multiple"
                                                    style="width:100%">
                                                @foreach ($products as $product)
                                                    <option value="{{ $product->id }}">
                                                        {{ $product->name }}
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                        <button type="submit" class="btn btn-primary">Create</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/jquery-file-upload.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
    <script src="{{ asset('vendors/summernote/dist/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('js/editorDemo.js') }}"></script>
    <script src="{{ asset('js/tabs.js') }}"></script>
    <script>
        $('.form-check-input').click(function () {
            $(this.form.elements).filter(':checkbox').prop('checked', this.checked);
        });
    </script>
    <script src="{{ asset('js/select2.js') }}"></script>
@stop

resources/views/admin/customers/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Customers edit
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('vendors/summernote/dist/summernote-bs4.css')}}">
@stop

@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row grid-margin">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-start justify-content-between">
                                <h4 class="card-title">Customers edit</h4>
                                <a href="{{ route("customers.index") }}" class="btn btn-primary btn-sm">Return to
                                    list</a>
                            </div>
                            @if(session()->has('success'))
                                <div class="alert alert-success">
                                    {{ session()->get('success') }}
                                </div>
                            @endif
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('customers.update', $customers->id) }}" method="POST">
                                @method('PATCH')
                                @csrf
                                <div class="form-group">
                                    <label for="name">Title</label>
                                    <input type="text" value="{{ $customers->name }}"
                                           name="name"
                                           class="form-control" id="name"
                                           placeholder="Name">
                                </div>
                                <div class="form-group">
                                    <label for="latitude">Latitude</label>
                                    <input type="number" step="any" value="{{ $customers->latitude }}"
                                           name="latitude" class="form-control" id="latitude">
                                </div>
                                <div class="form-group">
                                    <label for="longitude">Longitude</label>
                                    <input type="number" step="any" value="{{ $customers->longitude }}"
                                           name="longitude" class="form-control" id="longitude">
                                </div>
                                <div class="form-group ">
                                    <div class="form-group">
                                        <textarea id="description"
                                                  name="body">{{ $customers->description }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>List of related products</label>
                                    <select class="js-example-basic-multiple" name="products[]" multiple="multiple"
                                            style="width:100%">
                                        @foreach ($products as $product)
                                            <option value="{{ $product->id }}"
                                                    @if(in_array($product->id, $customers->product()->allRelatedIds()->toArray())) selected="selected" @endif>
                                                {{ $product->name }}
                                            </option>
                                        @endforeach
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/jquery-file-upload.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.10/js/select2.min.js"></script>
    <script src="{{ asset('vendors/summernote/dist/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('js/editorDemo.js') }}"></script>
    <script src="{{ asset('js/tabs.js') }}"></script>
    <script>
        $('.form-check-input').click(function () {
            $(this.form.elements).filter(':checkbox').prop('checked', this.checked);
        });
    </script>
    <script src="{{ asset('js/select2.js') }}"></script>
@stop

resources/views/admin/customers/list.blade.php
@extends('admin.layouts.app')

@section('title')
    Customers list
@stop

@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-start justify-content-between">
                                <h4 class="card-title">Customers list</h4>
                                <a href="{{ route("customers.create") }}" class="btn btn-success btn-sm">Create</a>
                            </div>
                            <div class="row">
                                <div class="table-sorter-wrapper col-lg-12 table-responsive">
                                    <table id="sortable-table-2" class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th class="sortStyle">Name<i class="mdi mdi-chevron-down"></i></th>
                                            <th>Description</th>
                                            <th>Latitude</th>
                                            <th>Longitude</th>
                                            <th class="sortStyle">Updated at<i class="mdi mdi-chevron-down"></i></th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($customers as $customer)
                                            <tr>
                                                <td>{{ $customer['id'] }}</td>
                                                <td><a href="#">{{ $customer->name }}</a></td>
                                                <td>{{ $customer->description }}</td>
                                                <td>{{ $customer->latitude }}</td>
                                                <td>{{ $customer->longitude }}</td>
                                                <td>{{ $customer->updated_at->toDateString() }}</td>
                                                <td>
                                                    <a href="{{ route('customers.edit',$customer['id'])}}"
                                                       class="btn btn-primary btn-sm">Edit</a>
                                                </td>
                                                <td>
                                                    <form action="{{ route('customers.destroy', $customer['id'])}}"
                                                          method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        @if ($customer->status == '0')
                                                            <button class="btn btn-success btn-sm"
                                                                    type="submit">
                                                                Activate
                                                            </button>
                                                        @elseif($customer->status == '1')
                                                            <button class="btn btn-outline-danger btn-sm" type="submit">
                                                                Deactivate
                                                            </button>
                                                        @endif
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{ $customers->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        <!-- partial -->
    </div>
    <!-- main-panel ends -->
@endsection

@section('scripts')
    <script src="{{ asset('js/jq.tablesort.js') }}"></script>
    <script src="{{ asset('js/tablesorter.js') }}"></script>
@endsection