routes/web.php
<?php

Auth::routes();

Route::group(['prefix' => '/'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('news', 'NewsController@index')->name('news-list');
    Route::get('news/{id}', 'NewsController@show')->name('news-show');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::get('reviews', 'ReviewController@index')->name('reviews');
    Route::post('mail', 'ContactController@sendEmail')->name('send-mail');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth',], function () {

    Route::get('/', 'Admin\HomeController@index')->name('admin.index');

    Route::resource('product', 'Admin\ProductController')->except([
        'show'
    ]);

    Route::resource('news', 'Admin\NewsController')->except([
        'show'
    ]);

    Route::resource('review', 'Admin\ReviewController')->except([
        'show'
    ]);

    Route::resource('contacts-email', 'Admin\ContactsEmailController')->except([
        'show'
    ]);

    Route::resource('contacts', 'Admin\ContactsController')->except([
        'show'
    ]);

    Route::resource('customers', 'Admin\CustomerController')->except([
        'show'
    ]);

    Route::post('image-upload/{id}', 'Admin\ProductImagesController@upload');

    Route::post('image-destroy/{id}', 'Admin\ProductImagesController@destroy');

    Route::post('image-store', 'Admin\ProductImagesController@store');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Carbon;

/**
 * App\Models\ProductRequest
 *
 * @property int $id
 * @property string $name
 * @property string $images
 * @property string $short_desc
 * @property string $body
 * @property string $status
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @method static Builder|Product newModelQuery()
 * @method static Builder|Product newQuery()
 * @method static Builder|Product query()
 * @method static Builder|Product whereBody($value)
 * @method static Builder|Product whereCreatedAt($value)
 * @method static Builder|Product whereId($value)
 * @method static Builder|Product whereImages($value)
 * @method static Builder|Product whereName($value)
 * @method static Builder|Product whereShortDesc($value)
 * @method static Builder|Product whereStatus($value)
 * @method static Builder|Product whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property-read Collection|\App\Models\Localized[] $localizedText
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Media[] $media
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Media[] $productImage
 * @property-read \App\Models\Media $productMainImage
 */
class Product extends Model
{
    /**
     * @var string
     */
    protected $table = "products";

    /**
     * @var array
     */
    protected $fillable = ['name', 'short_desc', 'body', 'status'];

    /**
     * @return HasMany
     */
    public function localizedText(): HasMany
    {
        return $this->hasMany(Localized::class, 'idx', 'id')->where('tbl_name', 'products');
    }

    /**
     * @return HasMany
     */
    public function productImage(): HasMany
    {
        return $this->HasMany(Media::class, 'model_id', 'id')->where('model_type', 'Products')
            ->where('collection_name', 'product_image');
    }

    /**
     * @return HasOne
     */
    public function productMainImage(): HasOne
    {
        return $this->HasOne(Media::class, 'model_id', 'id')->where('model_type', 'Products')
            ->where('collection_name', 'product_main_image');
    }

    /**
     * @param $lang
     * @return string|null
     */
    public function name($lang): ?string
    {
        switch ($lang) {
            case "az":
                $name = $this->localizedText->where('tbl_column_name', 'title')->first();
                if ($name != NULL)
                    return $name->az;
                else break;
            case "ru":
                $name = $this->localizedText->where('tbl_column_name', 'title')->first();
                if ($name != NULL)
                    return $name->ru;
                else break;
        }
        return null;
    }

    /**
     * @param $lang
     * @return string|null
     */
    public function body($lang): ?string
    {
        switch ($lang) {
            case "az":
                $body = $this->localizedText->where('tbl_column_name', 'body')->first();
                if ($body != NULL)
                    return $body->az;
                else break;
            case "ru":
                $body = $this->localizedText->where('tbl_column_name', 'body')->first();
                if ($body != NULL)
                    return $body->ru;
                else break;
        }
        return null;
    }

    /**
     * @param $lang
     * @return string|null
     */
    public function short_desc($lang): ?string
    {
        switch ($lang) {
            case "az":
                $short_desc = $this->localizedText->where('tbl_column_name', 'short_desc')->first();
                if ($short_desc != NULL)
                    return $short_desc->az;
                else break;
            case "ru":
                $short_desc = $this->localizedText->where('tbl_column_name', 'short_desc')->first();
                if ($short_desc != NULL)
                    return $short_desc->ru;
                else break;
        }
        return null;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Localized;
use App\Models\Media;
use App\Models\Product;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Illuminate\Support\Facades\Auth;

class ProductController extends Controller
{
    /**
     * ProductController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['only' => ['index', 'edit', 'update', 'store', 'destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $products = Product::paginate(10);
        return view('admin.products.list', compact('products'));
    }

    /**
     * @return Factory|View
     *
     */
    public function create()
    {
        return view('admin.products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ProductRequest $request
     * @return string
     */
    public function store(ProductRequest $request)
    {
        $product = new Product([
            'name'       => $request->get('title_en'),
            'short_desc' => $request->get('short_desc_en'),
            'body'       => $request->get('body_en'),
            'author_id'  => Auth::user()->id,
        ]);
        $product->save();

        if ($image = $request->file('image')) {
            foreach ($image as $files) {
                $destinationPath = 'media/product/'; // upload path
                if (!$files->move($destinationPath, $files->getClientOriginalName())) {
                    return 'Error saving the file.';
                }
                $form = new Media([
                    'model_type'      => 'Products',
                    'model_id'        => $product->id,
                    'collection_name' => 'product_image',
                    'file_name'       => $files->getClientOriginalName(),

                ]);
                $form->save();
            }
        }

        if ($image = $request->file('main_image')) {
            $destinationPath = 'media/product';
            if (!$image->move($destinationPath, $image->getClientOriginalName())) {
                return 'Error saving the file.';
            }
            $form = new Media([
                'model_type'      => 'Products',
                'model_id'        => $product->id,
                'collection_name' => 'product_main_image',
                'file_name'       => $image->getClientOriginalName(),
            ]);
            $form->save();
        }

        $product_local_title = new Localized([
            'tbl_name'        => 'products',
            'tbl_column_name' => 'title',
            'idx'             => $product->id,
            'ru'              => $request->get('title_ru'),
            'az'              => $request->get('title_az'),
        ]);

        $product_local_short_desc = new Localized([
            'tbl_name'        => 'products',
            'tbl_column_name' => 'short_desc',
            'idx'             => $product->id,
            'ru'              => $request->get('short_desc_ru'),
            'az'              => $request->get('short_desc_az'),
        ]);

        $product_local_body = new Localized([
            'tbl_name'        => 'products',
            'tbl_column_name' => 'body',
            'idx'             => $product->id,
            'ru'              => $request->get('body_ru'),
            'az'              => $request->get('body_az'),
        ]);
        $product_local_body->save();
        $product_local_short_desc->save();
        $product_local_title->save();

        return back()->with('success', 'ProductRequest has been added');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return void
     */
    public function edit(int $id)
    {
        $product = Product::FindorFail($id)->with('localizedText')->with('productImage')->where('id',
            $id)->firstOrFail();
        return view('admin.products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ProductRequest $request
     * @param int $id
     * @return string
     */
    public function update(ProductRequest $request, int $id)
    {
        $product = Product::findOrFail($id)->with('localizedText')->where('id', $id)->firstOrFail();
        $product->name = $request->get('title_en');
        $product->short_desc = $request->get('short_desc_en');
        $product->body = $request->get('body_en');
        if ($image = $request->file('main_image')) {
            $destinationPath = 'media/product';
            if (!$image->move($destinationPath, $image->getClientOriginalName())) {
                return 'Error saving the file.';
            }
            $form = new Media([
                'model_type'      => 'Products',
                'model_id'        => $product->id,
                'collection_name' => 'product_main_image',
                'file_name'       => $image->getClientOriginalName(),
            ]);
            $form->save();
        }
        $product->save();

        Localized::updateOrInsert(['idx' => $product->id, 'tbl_column_name' => 'title'], [
            'tbl_name'        => 'products',
            'tbl_column_name' => 'title',
            'az'              => $request->get('title_az'),
            'ru'              => $request->get('title_ru'),
        ]);

        Localized::updateOrInsert(['idx' => $product->id, 'tbl_column_name' => 'body'], [
            'tbl_name'        => 'products',
            'tbl_column_name' => 'body',
            'az'              => $request->get('body_az'),
            'ru'              => $request->get('body_ru'),
        ]);

        Localized::updateOrInsert(['idx' => $product->id, 'tbl_column_name' => 'short_desc'], [
            'tbl_name'        => 'products',
            'tbl_column_name' => 'short_desc',
            'az'              => $request->get('short_desc_az'),
            'ru'              => $request->get('short_desc_ru'),
        ]);

        return back()->with('success', 'ProductRequest has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy(int $id)
    {
        $product = Product::findorfail($id);
        if ($product->status == 0) {
            $product->status = '1';
        } elseif ($product->status == 1) {
            $product->status = '0';
        }
        $product->save();
        return back();
    }
}

resources/views/admin/products/create.blade.php
@extends('admin.layouts.app')

@section('title')
    Create product
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('admin_assets/vendors/summernote/dist/summernote-bs4.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.0/min/dropzone.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.5.0/dropzone.js"></script>
@stop

@section('content')
    <div class="main-panel" id="app">
        <div class="content-wrapper">
            <div class="row grid-margin">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-start justify-content-between">
                                <h4 class="card-title">Product create</h4>
                                <a href="{{ route("product.index") }}" class="btn btn-primary btn-sm">Return to list</a>
                            </div>
                            @if(session()->has('success'))
                                <div class="alert alert-success">
                                    {{ session()->get('success') }}
                                </div>
                            @endif
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif

                            <form action="{{ route('product.store') }}" enctype="multipart/form-data" method="POST">
                                @csrf
                                <div class="form-group">
                                    <label>Main image upload</label>
                                    <input style="display: block" type='file' id="main_image" name="main_image"
                                           accept=".png, .jpg, .jpeg"
                                    />
                                </div>
                                <ul class="nav nav-tabs" role="tablist">
                                    <li class="nav-item">
                                        <a class="nav-link active" id="contact-tab" data-toggle="tab" href="#en"
                                           role="tab" aria-controls="en" aria-selected="true">
                                            <i class="flag-icon flag-icon-us"></i> English
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="home-tab" data-toggle="tab" href="#az"
                                           role="tab" aria-controls="az" aria-selected="false">
                                            <i class="flag-icon flag-icon-az"></i> Azərbaycanca
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#ru"
                                           role="tab" aria-controls="ru" aria-selected="false">
                                            <i class="flag-icon flag-icon-ru"></i> Русcкий
                                        </a>
                                    </li>
                                </ul>
                                <div class="tab-content">
                                    <div class="tab-pane fade show active" id="en" role="tabpanel"
                                         aria-labelledby="en">
                                        <div class="media">
                                            <div class="tab-body">
                                                <div class="form-group">
                                                    <label for="title">Title</label>
                                                    <input type="text" value="{{Request::old('title_en')}}"
                                                           name="title_en"
                                                           class="form-control" id="title"
                                                           placeholder="Title">
                                                </div>
                                                <div class="form-group">
                                                    <label for="text">Short description</label>
                                                    <input type="text" value="{{Request::old('short_desc_en')}}"
                                                           name="short_desc_en" class="form-control" id="text"
                                                           placeholder="Short description">
                                                </div>
                                                <div class="form-group">
                                                <textarea id="summernote_en"
                                                          name="body_en">{{Request::old('body_en')}}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="az" role="tabpanel"
                                         aria-labelledby="az">
                                        <div class="media">
                                            <div class="tab-body">
                                                <div class="form-group">
                                                    <label for="title">Title</label>
                                                    <input type="text" value="{{Request::old('title_az')}}"
                                                           name="title_az"
                                                           class="form-control" id="title"
                                                           placeholder="Title">
                                                </div>
                                                <div class="form-group">
                                                    <label for="text">Short description</label>
                                                    <input type="text" value="{{Request::old('short_desc_az')}}"
                                                           name="short_desc_az" class="form-control" id="text"
                                                           placeholder="Short description">
                                                </div>
                                                <div class="form-group">
                                                <textarea id="summernote_az"
                                                          name="body_az">{{Request::old('body_az')}}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="ru" role="tabpanel"
                                         aria-labelledby="ru">
                                        <div class="media">
                                            <div class="tab-body">
                                                <div class="form-group">
                                                    <label for="title">Title</label>
                                                    <input type="text" value="{{Request::old('title_ru')}}"
                                                           name="title_ru"
                                                           class="form-control" id="title"
                                                           placeholder="Title">
                                                </div>
                                                <div class="form-group">
                                                    <label for="text">Short description</label>
                                                    <input type="text" value="{{Request::old('short_desc_ru')}}"
                                                           name="short_desc_ru" class="form-control" id="text"
                                                           placeholder="Short description">
                                                </div>
                                                <div class="form-group">
                                                <textarea id="summernote_ru"
                                                          name="body_ru">{{Request::old('body_ru')}}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="container">
                                    <h2>Laravel 6 Upload Image Using Dropzone Tutorial</h2><br/>
                                    <div id="dZUpload" class="dropzone">
                                        <div class="dz-default dz-message"></div>
                                    </div>
                                </div>
                                {{--                                <div class="form-group">--}}
                                {{--                                    <label>Images upload</label>--}}
                                {{--                                    <input style="display: block" type='file' id="image" name="image[]"--}}
                                {{--                                           accept=".png, .jpg, .jpeg"--}}
                                {{--                                           multiple/>--}}
                                {{--                                </div>--}}
                                <button type="submit" class="btn btn-primary">Create</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('admin_assets/js/jquery-file-upload.js') }}"></script>
    <script src="{{ asset('admin_assets/vendors/summernote/dist/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('admin_assets/js/editorDemo.js') }}"></script>
    <script src="{{ asset('admin_assets/js/tabs.js') }}"></script>
    <script>
        $('.form-check-input').click(function () {
            $(this.form.elements).filter(':checkbox').prop('checked', this.checked);
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            Dropzone.autoDiscover = false;
            $("#dZUpload").dropzone({
                url: "hn_SimpeFileUploader.ashx",
                addRemoveLinks: true,
                success: function (file, response) {
                    var imgName = response;
                    file.previewElement.classList.add("dz-success");
                    console.log("Successfully uploaded :" + imgName);
                },
                error: function (file, response) {
                    file.previewElement.classList.add("dz-error");
                }
            });
        });

    </script>
@stop

resources/views/admin/products/list.blade.php
@extends('admin.layouts.app')

@section('title')
    Products list
@stop

@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-start justify-content-between">
                                <h4 class="card-title">Products list</h4>
                                <a href="{{ route("product.create") }}" class="btn btn-success btn-sm">Create</a>
                            </div>
                            <div class="row">
                                <div class="table-sorter-wrapper col-lg-12 table-responsive">
                                    <table id="sortable-table-2" class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th class="sortStyle">Tittle<i class="mdi mdi-chevron-down"></i>
                                            </th>
                                            <th>Image</th>
                                            <th>Short description</th>
                                            <th class="sortStyle">Created at<i class="mdi mdi-chevron-down"></i></th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($products as $product)
                                            <tr>
                                                <td>{{ $product['id'] }}</td>
                                                <td class="lang_title">
                                                    <a href="#">{{ $product->name }}</a>
                                                </td>
                                                <td>
                                                    @if ($product->productMainImage)
                                                        <img src="{{ asset('media/product/' . $product->productMainImage->file_name) }}" alt="">
                                                    @endif
                                                </td>
                                                <td>{{ $product->short_desc }}</td>
                                                <td>{{ $product->created_at->toDateString() }}</td>
                                                <td>
                                                    <a href="{{ route('product.edit',$product['id'])}}"
                                                       class="btn btn-outline-primary btn-sm">Edit</a>
                                                </td>
                                                <td>
                                                    <form action="{{ route('product.destroy', $product['id'])}}"
                                                          method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        @if ($product->status == '0')
                                                            <button class="btn btn-outline-success btn-sm"
                                                                    type="submit">
                                                                Activate
                                                            </button>
                                                        @elseif($product->status == '1')
                                                            <button class="btn btn-outline-danger btn-sm" type="submit">
                                                                Deactivate
                                                            </button>
                                                        @endif
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{ $products->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        <!-- partial -->
    </div>
    <!-- main-panel ends -->
@endsection

@section('scripts')
    <script src="{{ asset('js/jq.tablesort.js') }}"></script>
    <script src="{{ asset('js/tablesorter.js') }}"></script>
@endsection