routes/web.php
<?php

Auth::routes();

Route::group(['prefix' => '/'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('news', 'NewsController@index')->name('news-list');
    Route::get('news/{id}', 'NewsController@show')->name('news-show');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::get('reviews', 'ReviewController@index')->name('reviews');
    Route::post('mail', 'ContactController@sendEmail')->name('send-mail');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth',], function () {

    Route::get('/', 'Admin\HomeController@index')->name('admin.index');

    Route::resource('product', 'Admin\ProductController')->except([
        'show'
    ]);

    Route::resource('news', 'Admin\NewsController')->except([
        'show'
    ]);

    Route::resource('review', 'Admin\ReviewController')->except([
        'show'
    ]);

    Route::resource('contacts-email', 'Admin\ContactsEmailController')->except([
        'show'
    ]);

    Route::resource('contacts', 'Admin\ContactsController')->except([
        'show'
    ]);

    Route::resource('customers', 'Admin\CustomerController')->except([
        'show'
    ]);

    Route::post('image-upload/{id}', 'Admin\ProductImagesController@upload');

    Route::post('image-destroy/{id}', 'Admin\ProductImagesController@destroy');

    Route::post('image-store', 'Admin\ProductImagesController@store');
});

app/Models/Contacts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;

/**
 * App\Models\Contacts
 *
 * @property int $id
 * @property string|null $address
 * @property string|null $phone
 * @property string|null $fax
 * @property string|null $emails
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @method static Builder|Contacts newModelQuery()
 * @method static Builder|Contacts newQuery()
 * @method static Builder|Contacts query()
 * @method static Builder|Contacts whereAddress($value)
 * @method static Builder|Contacts whereCreatedAt($value)
 * @method static Builder|Contacts whereEmails($value)
 * @method static Builder|Contacts whereFax($value)
 * @method static Builder|Contacts whereId($value)
 * @method static Builder|Contacts wherePhone($value)
 * @method static Builder|Contacts whereUpdatedAt($value)
 * @mixin \Eloquent
 * @property int $status
 * @method static Builder|Contacts whereStatus($value)
 */
class Contacts extends Model
{
    /**
     * @var string
     */
    protected $table = 'contacts';

    /**
     * @var array
     */
    protected $fillable = ['address', 'phone', 'fax', 'emails', 'status'];
}

app/Http/Controllers/Admin/ContactsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Contacts;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ContactsController extends Controller
{
    /**
     * ContactsController constructor.
     */
    public function __construct()
    {
        $this->middleware('auth', ['only' => ['index', 'edit', 'update', 'store', 'destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $contacts = Contacts::paginate(10);
        return view('admin.contacts.list', compact('contacts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.contacts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'address' => 'string|nullable',
            'phone'   => 'string|nullable',
            'fax'     => 'string|nullable',
            'emails'  => 'string|nullable',
        ]);

        $contacts = new Contacts([
            'address' => $request->get('address'),
            'phone'   => $request->get('phone'),
            'fax'     => $request->get('fax'),
            'emails'  => $request->get('emails'),
        ]);
        $contacts->save();

        return back()->with('success', 'Contacts has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Admin\Contacts $contacts
     * @return Response
     */
    public function show(Contacts $contacts)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit(int $id)
    {
        $contacts = Contacts::FindorFail($id);
        return view('admin.contacts.edit', compact('contacts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return void
     */
    public function update(Request $request, int $id)
    {
        $request->validate([
            'address' => 'string|nullable',
            'phone'   => 'string|nullable',
            'fax'     => 'string|nullable',
            'emails'  => 'string|nullable',
        ]);

        $contact = Contacts::findOrFail($id)->firstOrFail();
        $contact->address = $request->get('address');
        $contact->phone = $request->get('phone');
        $contact->fax = $request->get('fax');
        $contact->emails = $request->get('emails');
        $contact->save();

        return back()->with('success', 'Contacts has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy(int $id)
    {
        $contact = Contacts::findorfail($id);
        if ($contact->status == 0) {
            $contact->status = '1';
        } elseif ($contact->status == 1) {
            $contact->status = '0';
        }
        $contact->save();
        return back();
    }
}

app/Http/Controllers/ContactController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SendEmailRequest;
use App\Mail\ContactUs;
use Illuminate\Contracts\View\Factory;
use Illuminate\Support\Facades\Mail;
use Illuminate\View\View;

class ContactController extends Controller
{
    /**
     * @return Factory|View
     */
    public function index(): View
    {
        return view('pages.contacts');
    }

    public function sendEmail(SendEmailRequest $sendEmailRequest)
    {
        $validated = $sendEmailRequest->validated();

        Mail::send(new ContactUs($validated));

        return redirect()
            ->back()
            ->with('status', 'Thanks, your email has been successfully sent to us');
    }
}

resources/views/admin/contacts/create.blade.php
@extends('admin.layouts.app')

@section('title')
    Contacts create
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('vendors/summernote/dist/summernote-bs4.css')}}">
@stop

@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row grid-margin">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-start justify-content-between">
                                <h4 class="card-title">Contacts create</h4>
                                <a href="{{ route("contacts.index") }}" class="btn btn-primary btn-sm">Return to
                                    list</a>
                            </div>
                            @if(session()->has('success'))
                                <div class="alert alert-success">
                                    {{ session()->get('success') }}
                                </div>
                            @endif
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('contacts.store') }}"
                                  method="POST">
                                @csrf
                                <div class="form-group ">
                                    <div class="form-group">
                                        <label for="address">Address</label>
                                        <textarea id="summernote_address"
                                                  name="address">{{Request::old('address')}}</textarea>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <div class="form-group">
                                        <label for="phone">Phone</label>
                                        <textarea id="summernote_phone"
                                                  name="phone">{{Request::old('phone')}}</textarea>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <div class="form-group">
                                        <label for="fax">Fax</label>
                                        <textarea id="summernote_fax"
                                                  name="fax">{{Request::old('fax')}}</textarea>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <div class="form-group">
                                        <label for="emails">Emails</label>
                                        <textarea id="summernote_emails"
                                                  name="emails">{{Request::old('emails')}}</textarea>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Create</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/jquery-file-upload.js') }}"></script>
    <script src="{{ asset('vendors/summernote/dist/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('js/editorDemo.js') }}"></script>
    <script src="{{ asset('js/tabs.js') }}"></script>
    <script>
        $('.form-check-input').click(function () {
            $(this.form.elements).filter(':checkbox').prop('checked', this.checked);
        });
    </script>
@stop

resources/views/admin/contacts/edit.blade.php
@extends('admin.layouts.app')

@section('title')
    Contacts edit
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('vendors/summernote/dist/summernote-bs4.css')}}">
@stop

@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row grid-margin">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Contacts edit</h4>
                            @if(session()->has('success'))
                                <div class="alert alert-success">
                                    {{ session()->get('success') }}
                                </div>
                            @endif
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <form action="{{ route('contacts.update', $contacts->id) }}" method="POST">
                                @method('PATCH')
                                @csrf
                                <div class="form-group ">
                                    <div class="form-group">
                                        <label for="address">Address</label>
                                        <textarea id="summernote_address"
                                                  name="address">{{ $contacts->address }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <div class="form-group">
                                        <label for="phone">Phone</label>
                                        <textarea id="summernote_phone"
                                                  name="phone">{{ $contacts->phone }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <div class="form-group">
                                        <label for="fax">Fax</label>
                                        <textarea id="summernote_fax"
                                                  name="fax">{{ $contacts->fax }}</textarea>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <div class="form-group">
                                        <label for="emails">Emails</label>
                                        <textarea id="summernote_emails"
                                                  name="emails">{{ $contacts->emails }}</textarea>
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-primary">Update</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/jquery-file-upload.js') }}"></script>
    <script src="{{ asset('vendors/summernote/dist/summernote-bs4.min.js') }}"></script>
    <script src="{{ asset('js/editorDemo.js') }}"></script>
    <script src="{{ asset('js/tabs.js') }}"></script>
    <script>
        $('.form-check-input').click(function () {
            $(this.form.elements).filter(':checkbox').prop('checked', this.checked);
        });
    </script>
@stop

resources/views/admin/contacts/list.blade.php
@extends('admin.layouts.app')

@section('title')
    Contacts list
@stop

@section('content')
    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex align-items-start justify-content-between">
                                <h4 class="card-title">Contacts list</h4>
                                <a href="{{ route("contacts.create") }}" class="btn btn-success btn-sm">Create</a>
                            </div>
                            <div class="row">
                                <div class="table-sorter-wrapper col-lg-12 table-responsive">
                                    <table id="sortable-table-2" class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th>#</th>
                                            <th class="sortStyle">Name<i class="mdi mdi-chevron-down"></i></th>
                                            <th>Created at</th>
                                            <th>Updated at</th>
                                            <th>Actions</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach ($contacts as $contact)
                                            <tr>
                                                <td>{{ $contact['id'] }}</td>
                                                <td class="lang_title">
                                                    <a href="#">{!! $contact->address !!}</a>
                                                </td>
                                                <td>{{ $contact->created_at->toDateString() }}</td>
                                                <td>{{ $contact->updated_at->toDateString() }}</td>
                                                <td>
                                                    <a href="{{ route('contacts.edit',$contact['id'])}}"
                                                       class="btn btn-primary btn-sm">Edit</a>
                                                </td>
                                                <td>
                                                    <form action="{{ route('contacts.destroy', $contact['id'])}}"
                                                          method="post">
                                                        @csrf
                                                        @method('DELETE')
                                                        @if ($contact->status == '0')
                                                            <button class="btn btn-success btn-sm"
                                                                    type="submit">
                                                                Activate
                                                            </button>
                                                        @elseif($contact->status == '1')
                                                            <button class="btn btn-outline-danger btn-sm" type="submit">
                                                                Deactivate
                                                            </button>
                                                        @endif
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                                    {{ $contacts->links() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- content-wrapper ends -->
        <!-- partial:../../partials/_footer.html -->
        <!-- partial -->
    </div>
    <!-- main-panel ends -->
@endsection

@section('scripts')
    <script src="{{ asset('js/jq.tablesort.js') }}"></script>
    <script src="{{ asset('js/tablesorter.js') }}"></script>
@endsection