routes/web.php
<?php

Auth::routes();

Route::group(['prefix' => '/'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('news', 'NewsController@index')->name('news-list');
    Route::get('news/{id}', 'NewsController@show')->name('news-show');
    Route::get('contact', 'ContactController@index')->name('contact');
    Route::get('reviews', 'ReviewController@index')->name('reviews');
    Route::post('mail', 'ContactController@sendEmail')->name('send-mail');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth',], function () {

    Route::get('/', 'Admin\HomeController@index')->name('admin.index');

    Route::resource('product', 'Admin\ProductController')->except([
        'show'
    ]);

    Route::resource('news', 'Admin\NewsController')->except([
        'show'
    ]);

    Route::resource('review', 'Admin\ReviewController')->except([
        'show'
    ]);

    Route::resource('contacts-email', 'Admin\ContactsEmailController')->except([
        'show'
    ]);

    Route::resource('contacts', 'Admin\ContactsController')->except([
        'show'
    ]);

    Route::resource('customers', 'Admin\CustomerController')->except([
        'show'
    ]);

    Route::post('image-upload/{id}', 'Admin\ProductImagesController@upload');

    Route::post('image-destroy/{id}', 'Admin\ProductImagesController@destroy');

    Route::post('image-store', 'Admin\ProductImagesController@store');
});

resources/views/admin/includes/header.blade.php
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
    <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo" href="{{ route('admin.index') }}"><img src="{{ asset("admin_assets/images/panda_logo.png") }}" alt="logo"/></a>
        <a class="navbar-brand brand-logo-mini" style="color: white" href="{{ route('admin.index') }}">P</a>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
        {{--<ul class="navbar-nav mr-lg-2">
            <li class="nav-item nav-search d-none d-lg-block">
                <div class="input-group">
                    <div class="input-group-prepend">
                <span class="input-group-text" id="search">
                  <i class="mdi mdi-magnify"></i>
                </span>
                    </div>
                    <input type="text" class="form-control" placeholder="search" aria-label="search"
                           aria-describedby="search">
                </div>
            </li>
        </ul>--}}
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item nav-profile dropdown">
                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
                    <span class="nav-profile-name">{{ Auth::user()->name ?? '' }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
                    <a href="#" class="dropdown-item">
                        <i class="mdi mdi-settings text-primary"></i>
                        Settings
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ url('/logout') }}"
                       onclick="event.preventDefault();document.getElementById('logout-form').submit();"
                       class="dropdown-item">
                        <i class="mdi mdi-logout text-primary"></i>
                        Logout
                    </a>
                    <form id="logout-form" action="{{ url('/logout') }}"
                          method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </div>
            </li>
        </ul>
    </div>
</nav>

resources/views/admin/includes/menu.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ route('news.index') }}"
               aria-controls="news">
                <i class="mdi mdi-pencil menu-icon"></i>
                <span class="menu-title">News</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('customers.index') }}"
               aria-controls="customers">
                <i class="mdi mdi-account-multiple menu-icon"></i>
                <span class="menu-title">Customers</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('product.index') }}"
               aria-controls="product">
                <i class="mdi mdi-archive menu-icon"></i>
                <span class="menu-title">Products</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('review.index') }}"
               aria-controls="review">
                <i class="mdi mdi-inbox menu-icon"></i>
                <span class="menu-title">Reviews</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('contacts-email.index') }}"
               aria-controls="contacts-email">
                <i class="mdi mdi-contact-mail menu-icon"></i>
                <span class="menu-title">Contacts email</span>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ route('contacts.index') }}"
               aria-controls="contacts">
                <i class="mdi mdi-account-box-outline menu-icon"></i>
                <span class="menu-title">Contacts</span>
            </a>
        </li>
    </ul>
</nav>